Make rng an argument to ds
fralonra/ds-heightmap pull request #2
Opened 2023-06-01 00:04 UTC by hovatterz

I wanted to pass in a seeded rng. I'm not sure how to test the wasm build, but it's working great as a Rust crate. Hopefully this helps someone out in the future!

2023-06-01 05:34 UTC, fralonra commented
Hi, thanks for your contribution.

It's a great idea to pass rng as an argument.
But sometimes people might not care about the rng, passing in the rng everytime would be verbose.
In my opinion, it would be better to allow user to change the rng rather than forcing them to pass in rng.

For example:
```rust
let mut runner = Runner::with_rng(rng);

// or
let mut runner = Runner::new();
runner.set_rng(rng);
```

2023-06-01 13:14 UTC, hovatterz commented
I tried a few different angles to implement that, but I think that might be beyond me or it's too early in the morning ☕. Couldn't find a good way to store a mutable reference to `dyn rand::RngCore` while also allowing a default of `rand::thread_rng()` without making a mess of things.

Any thoughts?

2023-06-02 01:46 UTC, fralonra commented
How about these:
```rust
/// Run the Diamond-square algorithm.
pub fn ds(&mut self) -> Output; // Use a default rng

/// Run the Diamond-square algorithm with given rng.
pub fn ds_with_rng(&mut self, rng: &mut impl Rng) -> Output;
```

Then the rng should be passed to downstream, and no need to store it anymore.

2023-06-02 13:26 UTC, fralonra requested changes
Unify coding style.

2023-06-02 13:26 UTC, fralonra commented on rs/src/lib.rs
> +    /// Run the Diamond-square algorithm with a default rng.
Insert an empty line above.

2023-06-02 13:26 UTC, fralonra commented on rs/src/lib.rs
> +    pub fn ds_with_rng(&mut self, rng: &mut impl rand::Rng) -> Output {
`rand::Rng` is already imported, so just `Rng` here.

2023-06-02 13:26 UTC, fralonra commented on rs/src/lib.rs
> +    fn diamond(&mut self, x: f32, y: f32, half_w: f32, half_h: f32, rng: &mut impl rand::Rng) {
`rand::Rng` is already imported, so just `Rng` here.

2023-06-02 13:26 UTC, fralonra commented on rs/src/lib.rs
> +    fn randomize(&mut self, base: f32, range: f32, rng: &mut impl rand::Rng) -> f32 {
`rand::Rng` is already imported, so just `Rng` here.

2023-06-02 13:26 UTC, fralonra commented on rs/src/lib.rs
> +    fn square(&mut self, x: f32, y: f32, half_w: f32, half_h: f32, rng: &mut impl Rng) {
`rand::Rng` is already imported, so just `Rng` here.

2023-06-02 13:29 UTC, fralonra commented
> I sure overthought that one eh? Should be good to go now.

Sorry for the strictness, but I would like you to make more changes about the coding style.

Btw, it would be better if you could update the document for this feature! Thanks.

2023-06-02 13:37 UTC, hovatterz commented
No problem! I've been messing with this while working on my project, so I missed a few things there. Changes have been made. This doesn't apply to the WASM version so I updated the README in the rs dir.

2023-06-02 13:52 UTC, fralonra requested changes
The example in Readme is not runnable

2023-06-02 13:52 UTC, fralonra commented on rs/README.md
> +    let mut rng = ChaCha8Rng::from_entropy();
1. `ChaCha8Rng` is undeclared here.
2. `from_entropy` not found in `ChaCha8Rng`.

This example is not runnable.

2023-06-02 13:53 UTC, fralonra commented
> No problem! I've been messing with this while working on my project, so I missed a few things there. Changes have been made. This doesn't apply to the WASM version so I updated the README in the rs dir.

The exmaple you provided is not runnable.
Could you plz update it so that it can be copied and run without error?

2023-06-03 03:18 UTC, fralonra commented
Thanks for your patience.

### One more suggestion:
Use another random number generator instead of `ThreadRng`.

### Why
Since the `Runner::ds` is using `ThreadRng` internally, if we supply it into `Runner::ds_with_rng` again, users might not be awared of the fact that `Runner::ds()` is already using `ThreadRng`. Maybe some notes should be added. I can handle this, dont't worry.

### How
Previous example using `rand_chacha` is nice, except it's not runnable.
It can't compiled because you forgot to import something.
FYR, the below code compiles successfully.
```rust
use ds_heightmap::Runner;
use rand_chacha::{rand_core::SeedableRng, ChaCha8Rng};

fn main() {
    let mut rng = ChaCha8Rng::from_entropy();

    let mut runner = Runner::new();
    let output = runner.ds_with_rng(&mut rng);

    println!("data: {:?}", output.data);
    println!("max: {}", output.max);
    println!("min: {}", output.min);
}

```

2023-06-03 23:23 UTC, hovatterz commented
No worries! I'm a bit distracted while trying to make these revisions so my bad on that.

2023-06-04 01:44 UTC, fralonra commented
Great works!
Thanks you for your contribution!

2023-06-04 01:44 UTC, merged

2023-06-04 17:00 UTC, fralonra reviewed
Merged